"""ATNLPtf_syntacticalGraph.py

# Author:
Richard Bruce Baxter - Copyright (c) 2020-2022 Baxter AI (baxterai.com)

# License:
MIT License

# Installation:
see ATNLPtf_main.py

# Usage:
see ATNLPtf_main.py

# Description:
ATNLP Syntactical Graph - generate syntactical tree/graph using input vectors (based on word proximity, frequency, and recency heuristics)

ATNLP (or SANI) syntactical tree stucture is generated in a format similar to a constituency-based parse tree

"""

import numpy as np
import spacy
spacyWordVectorGenerator = spacy.load('en_core_web_md')	#spacy.load('en_core_web_lg')
import ANNtf2_loadDataset
from ATNLPtf_syntacticalNodeClass import *
import ATNLPtf_semanticGraphIntermediaryTransformation
	
drawSyntacticalGraphSentence = True
if(drawSyntacticalGraphSentence):
	import ATNLPtf_syntacticalGraphDraw as ATNLPtf_syntacticalGraphDrawSentence
drawSyntacticalGraphNetwork	= True	#draw graph for entire network (not just sentence)
if(drawSyntacticalGraphNetwork):
	import ATNLPtf_syntacticalGraphDraw as ATNLPtf_syntacticalGraphDrawNetwork
drawSyntacticalGraphNodeColours = False
if(drawSyntacticalGraphNodeColours):
	from ATNLPtf_semanticNodeClass import identifyEntityType

performReferenceResolution = True

calibrateConnectionMetricParameters = True
printVerbose = False

#calculateFrequencyConnection method: calculates frequency of co-occurance of words/subsentences in corpus 
calculateConnectionFrequencyUsingWordVectorSimilarity = True	#mandatory	#CHECKTHIS requires update - currently uses rudimentary word vector similarity comparison
calculateReferenceFrequencyUsingWordVectorSimilarity = True	#optional	#else calculate reference similarity using calculateSubgraphNumberIdenticalConcepts

calculateConnectionFrequencyBasedOnNodeSentenceSubgraphsDynamic = False	#optional (not required to compare hidden node similarity as artificial word vectors are generated for new hidden nodes in sentence)	#else getBranchWordVector (flat)
calculateConnectionRecencyBasedOnNodeSentenceSubgraphsDynamic = False	#optional (not required to compare hidden node concept recency as artificial concept recency values are generated for new hidden nodes in sentence)		#else getBranchConceptTime (flat)
if(calculateReferenceFrequencyUsingWordVectorSimilarity):
	calculateReferenceFrequencyBasedOnNodeSentenceSubgraphsDynamic = False	#mandatory
else:
	calculateReferenceFrequencyBasedOnNodeSentenceSubgraphsDynamic = True	#mandatory
calculateReferenceRecencyBasedOnNodeSentenceSubgraphsDynamic = False	#mandatory

calculateFrequencyBasedOnNodeSentenceSubgraphsDynamicEmulate = True	#optional - branch wordVector calculated based on average of leafNode wordVectors, else average of previous branch wordVectors
calculateRecencyBasedOnNodeSentenceSubgraphsDynamicEmulate = True	#optional - branch conceptTime calculated based on average of leafNode conceptTime, else average of previous branch conceptTimes

#addSyntacticalConceptNodesToGraph = False	#add concept to dictionary (if non-existent) - not currently used (concept nodes generated by ATNLPtf_semanticGraph only)
#contiguousNodesGraph = True 	#mandatory: nodes must be contiguous (word order)

conceptID = 0	#special instance ID for concepts
maxTimeDiff = 10.0	#calculateTimeDiff(minRecency)	#CHECKTHIS: requires calibration (<= ~10: ensures timeDiff for unencountered concepts is not infinite - required for metric)	#units: sentenceIndex
#minRecency = calculateRecency(maxTimeDiff)	#  minRecency = 0.1	#CHECKTHIS: requires calibration (> 0: ensures recency for unencountered concepts is not zero - required for metric)	
maxRecency = 1.0
maxTimeDiffForMatchingInstance = 2	#time in sentence index diff	#CHECKTHIS: requires calibration
metricThresholdToCreateConnection = 0.0	#CHECKTHIS: requires calibration
metricThresholdToCreateReference = 1.0	#CHECKTHIS: requires calibration

graphNodeDictionary = {}	#dict indexed by lemma, every entry is a dictionary of SyntacticalNode instances indexed by instanceID (first instance is special; reserved for concept)
#graphConnectionsDictionary = {}	#dict indexed tuples (lemma1, instanceID1, lemma2, instanceID2), every entry is a tuple of SyntacticalNode instances/concepts (instanceNode1, instanceNode2) [directionality: 1=source, 2=target]
	#this is used for visualisation/fast lookup purposes only - can trace node graphNodeTargetList/graphNodeSourceList instead

headNodeList = []

def generateSyntacticalGraphNetwork(articles, performIntermediarySemanticTransformation, generateSyntacticalGraphNetwork):

	for sentenceIndex, sentence in enumerate(articles):
		generateSyntacticalGraphSentenceString(sentenceIndex, sentence, performIntermediarySemanticTransformation, generateSyntacticalGraphNetwork)		
	
	return graphNodeDictionary	#, graphConnectionsDictionary
	
def generateSyntacticalGraphSentenceString(sentenceIndex, sentence, performIntermediarySemanticTransformation, generateSyntacticalGraphNetwork):

	print("\n\ngenerateSyntacticalGraphSentenceString: sentenceIndex = ", sentenceIndex, "; ", sentence)

	tokenisedSentence = tokeniseSentence(sentence)
	sentenceLength = len(tokenisedSentence)

	if(sentenceLength > 1):
		return generateSyntacticalGraphSentence(sentenceIndex, tokenisedSentence, performIntermediarySemanticTransformation, generateSyntacticalGraphNetwork)
	else:
		print("error: sentenceLength !> 1")
		exit()
			
def generateSyntacticalGraphSentence(sentenceIndex, tokenisedSentence, performIntermediarySemanticTransformation, generateSyntacticalGraphNetwork):

	ATNLPtf_syntacticalGraphDrawSentence.setColourSyntacticalNodes(drawSyntacticalGraphNodeColours)
	print("ATNLPtf_syntacticalGraph: ATNLPtf_syntacticalGraphDrawSentence.drawSyntacticalGraphNodeColours = ", ATNLPtf_syntacticalGraphDrawSentence.drawSyntacticalGraphNodeColours)
	
	currentTime = calculateActivationTime(sentenceIndex)

	if(drawSyntacticalGraphSentence):
		ATNLPtf_syntacticalGraphDrawSentence.clearSyntacticalGraph()
	if(generateSyntacticalGraphNetwork):
		if(drawSyntacticalGraphNetwork):
			ATNLPtf_syntacticalGraphDrawNetwork.clearSyntacticalGraph()
			
	sentenceLeafNodeList = []	#local/temporary list of sentence instance nodes (before reference resolution)		
	sentenceTreeNodeList = []	#local/temporary list of sentence instance nodes (before reference resolution)
	connectivityStackNodeList = []	#temporary list of nodes on connectivity stack
	#sentenceGraphNodeDictionary = {}	#local/isolated/temporary graph of sentence instance nodes (before reference resolution)
		
	sentenceLength = len(tokenisedSentence)
	
	#declare graph nodes;
	for w, token in enumerate(tokenisedSentence):	

		#primary vars;
		word = getTokenWord(token)
		lemma = getTokenLemma(token)
		wordVector = getTokenWordVector(token)	#numpy word vector
		posTag = getTokenPOStag(token)
		activationTime = calculateActivationTime(sentenceIndex)
		nodeGraphType = graphNodeTypeLeaf
		
		#sentenceTreeArtificial vars;
		subgraphSize = 1
		conceptWordVector = wordVector
		conceptTime = calculateConceptTimeLeafNode(sentenceLeafNodeList, lemma, currentTime)	#units: min time diff (not recency metric)
		treeLevel = 0

		#if(addSyntacticalConceptNodesToGraph):
		#	#add concept to dictionary (if non-existent) - not currently used;
		#	if lemma not in graphNodeDictionary:
		#		instanceID = conceptID
		#		conceptNode = SyntacticalNode(instanceID, word, lemma, wordVector, posTag, nodeGraphType, currentTime, subgraphSize, conceptWordVector, conceptTime, w, w, w, treeLevel, sentenceIndex)
		#		addInstanceNodeToGraph(lemma, instanceID, conceptNode)

		#add instance to local/temporary sentenceLeafNodeList (reference resolution is required before adding nodes to graph);
		instanceID = getNewInstanceID(lemma)	#same instance id will be assigned to identical lemmas in sentence (which is not approprate in the case they refer to independent instances) - will be reassign instance id after reference resolution
		instanceNode = SyntacticalNode(instanceID, word, lemma, wordVector, posTag, nodeGraphType, currentTime, subgraphSize, conceptWordVector, conceptTime, w, w, w, treeLevel, sentenceIndex)
		addInstanceNodeToGraph(lemma, instanceID, instanceNode)
		if(printVerbose):
			print("create new instanceNode; ", instanceNode.lemma, ": instanceID=", instanceNode.instanceID)

		#connection vars;
		sentenceLeafNodeList.append(instanceNode)
		sentenceTreeNodeList.append(instanceNode)
		connectivityStackNodeList.append(instanceNode)

		if(drawSyntacticalGraphNodeColours):	
			entityType = identifyEntityType(instanceNode)
			instanceNode.entityType = entityType
		if(drawSyntacticalGraphSentence):
			ATNLPtf_syntacticalGraphDrawSentence.drawSyntacticalGraphNode(instanceNode, w, treeLevel)

	#add connections to local/isolated/temporary graph (syntactical tree);
	if(calibrateConnectionMetricParameters):
		recencyList = []
		proximityList = []
		frequencyList = []	
		metricList = []

	headNodeFound = False
	graphHeadNode = None
	while not headNodeFound:

		connectionNode1 = None
		connectionNode2 = None
		maxConnectionMetric = 0.0

		connectionFound = False

		for node1StackIndex, node1 in enumerate(connectivityStackNodeList):
			for node2StackIndex, node2 in enumerate(connectivityStackNodeList):
				if(node1StackIndex != node2StackIndex):
					#print("node1.wMax = ", node1.wMax)
					#print("node2.wMin = ", node2.wMin)
					if(node1.wMax+1 == node2.wMin):
						if(printVerbose):
							print("calculateMetricConnection: node1.lemma = ", node1.lemma, ", node2.lemma = ", node2.lemma)
						proximity = calculateProximityConnection(node1.w, node2.w)
						frequency = calculateFrequencyConnection(sentenceTreeNodeList, node1, node2)
						recency = calculateRecencyConnection(sentenceTreeNodeList, node1, node2, currentTime)	#minimise the difference in concept last access recency between left/right node
						connectionMetric = calculateMetricConnection(proximity, frequency, recency)
						if(connectionMetric > metricThresholdToCreateConnection):
							if(connectionMetric > maxConnectionMetric):
								#print("connectionMetric found")
								connectionFound = True
								maxConnectionMetric = connectionMetric
								connectionNode1 = node1
								connectionNode2 = node2
						
						if(calibrateConnectionMetricParameters):
							proximityList.append(proximity)
							frequencyList.append(frequency)
							recencyList.append(recency)
							metricList.append(connectionMetric)
			
		if(not connectionFound):
			print("error connectionFound - check calculateMetricConnection parameters > 0.0, maxConnectionMetric = ", maxConnectionMetric)
			exit()

		if(printVerbose):
			print("create connection; w1 w2 = ", connectionNode1.w, " ", connectionNode2.w, ", connectionNode1.lemma connectionNode2.lemma = ", connectionNode1.lemma, " ", connectionNode2.lemma, ", metric = ", maxConnectionMetric)

		#CHECKTHIS limitation - infers directionality (source/target) of connection based on w1/w2 word order		
		connectionDirection = True	#CHECKTHIS: always assume left to right directionality

		#primary vars;
		word = connectionNode1.word + connectionNode2.word
		lemma = connectionNode1.lemma + connectionNode2.lemma
		wordVector = getBranchWordVectorFromSourceNodes(connectionNode1, connectionNode2)
		posTag = None
		activationTime = calculateActivationTime(sentenceIndex)	#mean([connectionNode1.activationTime, connectionNode2.activationTime]) 
		nodeGraphType = graphNodeTypeBranch

		#sentenceTreeArtificial vars;
		subgraphSize = connectionNode1.subgraphSize + connectionNode2.subgraphSize + 1
		conceptWordVector = np.add(connectionNode1.conceptWordVector, connectionNode2.conceptWordVector)
		conceptTime = connectionNode1.conceptTime + connectionNode2.conceptTime
		treeLevel = max(connectionNode1.treeLevel, connectionNode2.treeLevel) + 1
		w = mean([connectionNode1.w, connectionNode2.w])
		wMin = min(connectionNode1.wMin, connectionNode2.wMin)
		wMax = max(connectionNode1.wMax, connectionNode2.wMax)

		instanceID = getNewInstanceID(lemma)
		hiddenNode = SyntacticalNode(instanceID, word, lemma, wordVector, posTag, nodeGraphType, currentTime, subgraphSize, conceptWordVector, conceptTime, w, wMin, wMax, treeLevel, sentenceIndex)
		addInstanceNodeToGraph(lemma, instanceID, hiddenNode)
		
		#connection vars;
		createGraphConnectionWrapper(hiddenNode, connectionNode1, connectionNode2, connectionDirection, addToConnectionsDictionary=False)
		sentenceTreeNodeList.append(hiddenNode)
		connectivityStackNodeList.remove(connectionNode1)
		connectivityStackNodeList.remove(connectionNode2)
		connectivityStackNodeList.append(hiddenNode)

		if(drawSyntacticalGraphSentence):
			ATNLPtf_syntacticalGraphDrawSentence.drawSyntacticalGraphNode(hiddenNode, w, treeLevel)
			ATNLPtf_syntacticalGraphDrawSentence.drawSyntacticalGraphConnection(hiddenNode, connectionNode1)
			ATNLPtf_syntacticalGraphDrawSentence.drawSyntacticalGraphConnection(hiddenNode, connectionNode2)

		if(len(connectivityStackNodeList) == 1):
			headNodeFound = True
			hiddenNode.graphNodeType = graphNodeTypeHead	#reference set delimiter (captures primary subject/action/object of sentence clause)
			graphHeadNode = hiddenNode
			headNodeList.append(graphHeadNode)

	if(drawSyntacticalGraphSentence):
		print("ATNLPtf_syntacticalGraphDrawSentence.displaySyntacticalGraph()")
		ATNLPtf_syntacticalGraphDrawSentence.displaySyntacticalGraph()
		
	if(performIntermediarySemanticTransformation):
		ATNLPtf_semanticGraphIntermediaryTransformation.performIntermediarySemanticTransformation(sentenceLeafNodeList, sentenceTreeNodeList, graphHeadNode)
			
	if(calibrateConnectionMetricParameters):
		proximityMinMeanMax = minMeanMaxList(proximityList)
		frequencyMinMeanMax = minMeanMaxList(frequencyList)
		recencyMinMeanMax = minMeanMaxList(recencyList)
		metricMinMeanMax = minMeanMaxList(metricList)
		print("proximityMinMeanMax = ", proximityMinMeanMax)
		print("frequencyMinMeanMax = ", frequencyMinMeanMax)
		print("recencyMinMeanMax = ", recencyMinMeanMax)
		print("metricMinMeanMax = ", metricMinMeanMax)
			
	if(generateSyntacticalGraphNetwork):
		if(performReferenceResolution):
			#peform reference resolution after building syntactical tree (any instance of successful reference identification will insert syntactical tree into syntactical graph/network)
			identifyBranchReferences(sentenceTreeNodeList, graphHeadNode, currentTime)

		if(drawSyntacticalGraphNetwork):
			ATNLPtf_syntacticalGraphDrawNetwork.drawSyntacticalGraphNetwork(headNodeList)
			print("ATNLPtf_syntacticalGraphDrawNetwork.displaySyntacticalGraph()")
			ATNLPtf_syntacticalGraphDrawNetwork.displaySyntacticalGraph()
				
	return sentenceLeafNodeList, sentenceTreeNodeList, graphHeadNode



#node:

def createSubDictionaryForConcept(dic, lemma):
	dic[lemma] = {}	#create empty dictionary for new concept
			
def findInstanceNodeInGraph(lemma, instanceID):
	node = graphNodeDictionary[lemma][instanceID]
	return node

def addInstanceNodeToGraph(lemma, instanceID, node):
	addInstanceNodeToDictionary(graphNodeDictionary, lemma, instanceID, node)

def addInstanceNodeToDictionary(dic, lemma, instanceID, node):
	if lemma not in dic:
		createSubDictionaryForConcept(dic, lemma)
	dic[lemma][instanceID] = node

def isInstanceNodeInGraph(node):
	return isInstanceNodeInDictionary(graphNodeDictionary, node)
	
def isInstanceNodeInDictionary(dic, node):
	if node.lemma not in dic:
		createSubDictionaryForConcept(dic, node.lemma)
	if(node in dic[node.lemma]):
		result = True
	else:
		result = False
	return result
	
def getNewInstanceID(lemma):
	if lemma in graphNodeDictionary:
		#newInstanceID = len(graphNodeDictionary[lemma])	#not reliable in the event a sentence node temporarily added to dictionary was referenced and removed from dictionary
		if(len(graphNodeDictionary[lemma]) > 0):
			lastInstanceIDadded = list(graphNodeDictionary[lemma])[-1]	#get last element inserted in dictionary (will have highest instanceID) - requires Python 3.7
			newInstanceID = lastInstanceIDadded+1
		else:
			newInstanceID = 0
	else:
		newInstanceID = 0
	return newInstanceID

def removeNodeFromGraph(node):
	nodeConceptInstances = graphNodeDictionary[node.lemma]
	nodeConceptInstances.pop(node.instanceID) 

#connection:

def createGraphConnectionWrapper(hiddenNode, node1, node2, connectionDirection, addToConnectionsDictionary=True):
	if(connectionDirection):
		createGraphConnection(hiddenNode, node1, node2, addToConnectionsDictionary)
	else:
		createGraphConnection(hiddenNode, node2, node1, addToConnectionsDictionary)
		
def createGraphConnection(hiddenNode, node1, node2, addToConnectionsDictionary):
	addConnectionToNodeTargets(node1, hiddenNode)
	addConnectionToNodeTargets(node2, hiddenNode)
	addConnectionToNodeSources(hiddenNode, node1)
	addConnectionToNodeSources(hiddenNode, node2)
	node1.sourceNodePosition = sourceNodePositionFirst
	node2.sourceNodePosition = sourceNodePositionSecond

	#if(addToConnectionsDictionary):
	#	graphConnectionKey = createGraphConnectionKey(hiddenNode, node1, node2)
	#	graphConnectionsDictionary[graphConnectionKey] = (hiddenNode, node1, node2)

#def createGraphConnectionKey(hiddenNode, node1, node2):
#	connectionKey = (hiddenNode.lemma, hiddenNode.instanceID, node1.lemma, node1.instanceID, node2.lemma, node2.instanceID)
#	return connectionKey



#metric:

def calculateMetricReference(frequency, recency):
	#print("\tfrequency = ", frequency)
	#print("\trecency = ", recency)
	metric = frequency*recency #CHECKTHIS: requires calibration - normalisation of factors is required
	#print("\tmetric = ", metric)
	return metric
		
def calculateMetricConnection(proximity, frequency, recency):
	metric = proximity*frequency*recency #CHECKTHIS: requires calibration - normalisation of factors is required
	#print("\t\tcalculateMetricConnection: metric = ", metric, "; proximity = ", proximity, ", frequency = ", frequency, ", recency = ", recency)
	return metric
	
	
	
#proximity:

def calculateProximityConnection(w, w2):
	proximity = 1.0 / abs(w-w2)	#CHECKTHIS: requires calibration
	#proximity = 1.0	#complete deweight of proximity parameter
	return proximity



#frequency:

#frequency reference:
def calculateFrequencyReference(sentenceTreeNodeList, node1, node2):
	#CHECKTHIS: requires calibration
	#CHECKTHIS; note compares node subgraph source components (not target components)
	frequency = compareNodeReferenceSimilarity(sentenceTreeNodeList, node1, node2)	 #CHECKTHIS requires update - currently uses rudimentary word vector similarity comparison
	return frequency

def compareNodeReferenceSimilarity(sentenceTreeNodeList, node1, node2):
	if(calculateReferenceFrequencyUsingWordVectorSimilarity):
		similarity = compareNodeWordVectorsSimilarity(sentenceTreeNodeList, node1, node2, calculateReferenceFrequencyBasedOnNodeSentenceSubgraphsDynamic)		#compareNodeCorpusAssociationFrequency
	else:
		similarity = compareNodeIdenticalConceptSimilarity(sentenceTreeNodeList, node1, node2, calculateReferenceFrequencyBasedOnNodeSentenceSubgraphsDynamic)
	return similarity
	
#frequency connection:
def calculateFrequencyConnection(sentenceTreeNodeList, node1, node2):
	#CHECKTHIS: requires calibration
	#CHECKTHIS; note compares node subgraph source components (not target components)
	frequency = compareNodeConnectionSimilarity(sentenceTreeNodeList, node1, node2)	 #CHECKTHIS requires update - currently uses rudimentary word vector similarity comparison
	return frequency

def compareNodeConnectionSimilarity(sentenceTreeNodeList, node1, node2):
	if(calculateConnectionFrequencyUsingWordVectorSimilarity):
		similarity = compareNodeWordVectorsSimilarity(sentenceTreeNodeList, node1, node2, calculateConnectionFrequencyBasedOnNodeSentenceSubgraphsDynamic)		#compareNodeCorpusAssociationFrequency
	else:
		print("compareNodeConnectionSimilarity currently requires calculateConnectionFrequencyUsingWordVectorSimilarity - no alternate method coded")
		exit()
	return similarity

#frequency metric 1 (word vector similarity):
def compareNodeWordVectorsSimilarity(sentenceTreeNodeList, node1, node2, nodeSentenceSubgraphsDynamic):
	wordVectorDiff = compareNodeWordVectors(sentenceTreeNodeList, node1, node2, nodeSentenceSubgraphsDynamic)
	#print("compareNodeWordVectorsSimilarity: node1.lemma = ", node1.lemma, ", node2.lemma = ", node2.lemma, ", wordVectorDiff = ", wordVectorDiff)
	similarity = calculateWordVectorSimilarity(wordVectorDiff)
	return similarity
	
def compareNodeWordVectors(sentenceTreeNodeList, node1, node2, nodeSentenceSubgraphsDynamic):
	if(nodeSentenceSubgraphsDynamic):
		subgraphArtificalWordVector1 = calculateSubgraphArtificialWordVector(sentenceTreeNodeList, node1)
		subgraphArtificalWordVector2 = calculateSubgraphArtificialWordVector(sentenceTreeNodeList, node2)
	else:
		subgraphArtificalWordVector1 = getBranchWordVector(node1)
		subgraphArtificalWordVector2 = getBranchWordVector(node2)
	wordVectorDiff = compareWordVectors(subgraphArtificalWordVector1, subgraphArtificalWordVector2)		
	return wordVectorDiff
	
def calculateSubgraphArtificialWordVector(sentenceTreeNodeList, node):
	subgraphArtificalWordVector = np.zeros(shape=ANNtf2_loadDataset.wordVectorLibraryNumDimensions)
	subgraphArtificalWordVector, subgraphSize = calculateSubgraphArtificialWordVectorRecurse(sentenceTreeNodeList, node, subgraphArtificalWordVector, 0)	
	subgraphArtificalWordVector = np.divide(subgraphArtificalWordVector, float(subgraphSize))
	return subgraphArtificalWordVector

def calculateSubgraphArtificialWordVectorRecurse(sentenceTreeNodeList, node, subgraphArtificalWordVector, subgraphSize):
	#CHECKTHIS: requires update - currently uses rudimentary combined word vector similarity comparison
	if(node.graphNodeType == graphNodeTypeLeaf):
		subgraphArtificalWordVector = np.add(subgraphArtificalWordVector, node.wordVector)
		#print("subgraphArtificalWordVector = ", np.mean(np.abs(subgraphArtificalWordVector)))
		subgraphSize = subgraphSize + 1
	for subgraphNode in node.graphNodeSourceList:	
		#if(subgraphNode in sentenceTreeNodeList):	#verify subgraph instance was referenced in current sentence
		subgraphArtificalWordVector, subgraphSize = calculateSubgraphArtificialWordVectorRecurse(sentenceTreeNodeList, subgraphNode, subgraphArtificalWordVector, subgraphSize)
	return subgraphArtificalWordVector, subgraphSize
	
def calculateWordVectorSimilarity(wordVectorDiff):
	similarity = 1.0 - wordVectorDiff
	#print("similarity = ", similarity)
	return similarity

def compareWordVectors(wordVector1, wordVector2):
	wordVectorDiff = np.mean(np.absolute(np.subtract(wordVector1, wordVector2)))
	#print("\twordVector1 = ", wordVector1)
	#print("\twordVector2 = ", wordVector2)
	return wordVectorDiff

def getBranchWordVectorFromSourceNodes(connectionNode1, connectionNode2):
	if(calculateFrequencyBasedOnNodeSentenceSubgraphsDynamicEmulate):
		wordVector = np.divide(np.add(connectionNode1.conceptWordVector, connectionNode2.conceptWordVector), (connectionNode1.subgraphSize + connectionNode2.subgraphSize))
	else:
		wordVector = np.divide(np.add(connectionNode1.wordVector, connectionNode2.wordVector), 2.0)
	return wordVector

def getBranchWordVector(node1):
	if(calculateFrequencyBasedOnNodeSentenceSubgraphsDynamicEmulate):
		wordVector = np.divide(node1.conceptWordVector, node1.subgraphSize)
	else:
		wordVector = np.divide(node1.wordVector)
	return wordVector

#frequency metric 2 (identical concept similarity):
def compareNodeIdenticalConceptSimilarity(sentenceTreeNodeList, node1, node2, nodeSentenceSubgraphsDynamic):
	if(nodeSentenceSubgraphsDynamic):
		similarity = calculateSubgraphNumberIdenticalConcepts(sentenceTreeNodeList, node1, node2)			
	else:
		print("compareNodeIdenticalConceptSimilarity currently requires nodeSentenceSubgraphsDynamic - no alternate method coded")
		exit()
	return similarity

def calculateSubgraphNumberIdenticalConcepts(sentenceTreeNodeList, node1, nodeToCompare):
	numberOfIdenticalConcepts, subgraphSize = calculateSubgraphNumberIdenticalConcepts1(sentenceTreeNodeList, node1, nodeToCompare, 0, 0)
	similarity = numberOfIdenticalConcepts/subgraphSize
	return similarity
	
#compares all nodes in node1 subgraph (to nodeToCompare subgraphs)
#recurse node1 subgraph
def calculateSubgraphNumberIdenticalConcepts1(sentenceTreeNodeList, node1, nodeToCompare, numberOfIdenticalConcepts1, subgraphSize):
	#TODO: verify calculate source to target connections only
	numberOfIdenticalConcepts2 = calculateSubgraphNumberIdenticalConcepts2(sentenceTreeNodeList, node1, nodeToCompare, 0)
	numberOfIdenticalConcepts1 += numberOfIdenticalConcepts2
	subgraphSize = subgraphSize + 1
	for subgraphNode1 in node1.graphNodeSourceList:	
		if(subgraphNode1 in sentenceTreeNodeList):	#verify subgraph instance was referenced in current sentence
			numberOfIdenticalConcepts1, subgraphSize = calculateSubgraphNumberIdenticalConcepts1(sentenceTreeNodeList, subgraphNode1, nodeToCompare, numberOfIdenticalConcepts1, subgraphSize)
	return numberOfIdenticalConcepts1, subgraphSize

#compares node1 with all nodes in node2 subgraph
#recurse node2 subgraph
def calculateSubgraphNumberIdenticalConcepts2(sentenceTreeNodeList, node1, node2, numberOfIdenticalConcepts):
	#TODO: verify calculate source to target connections only
	if(node1.lemma == node2.lemma):
		numberOfIdenticalConcepts += 1
	for subgraphNode2 in node2.graphNodeSourceList:	
		if(subgraphNode2 not in sentenceTreeNodeList):	#verify subgraph instance was not referenced in current sentence
			numberOfIdenticalConcepts = calculateSubgraphNumberIdenticalConcepts2(sentenceTreeNodeList, node1, subgraphNode2, numberOfIdenticalConcepts)
	return numberOfIdenticalConcepts



#recency:

#recency reference:	
def calculateRecencyReference(sentenceTreeNodeList, node1, node2, currentTime):
	#calculates recency based on concept last access time - no alternate method coded
	recency = compareNodeConceptTimeSimilarity(sentenceTreeNodeList, node1, node2, currentTime, calculateReferenceRecencyBasedOnNodeSentenceSubgraphsDynamic)
	return recency
	
#recency connection:
def calculateRecencyConnection(sentenceTreeNodeList, node1, node2, currentTime):
	#calculates recency based on concept last access time - no alternate method coded
	recency = compareNodeConceptTimeSimilarity(sentenceTreeNodeList, node1, node2, currentTime, calculateConnectionRecencyBasedOnNodeSentenceSubgraphsDynamic)
	return recency
	
#recency metric:	
def compareNodeConceptTimeSimilarity(sentenceTreeNodeList, node1, node2, currentTime, nodeSentenceSubgraphsDynamic):
	timeDiff = compareNodeConceptTime(sentenceTreeNodeList, node1, node2, currentTime, nodeSentenceSubgraphsDynamic)
	recencySimilarity = calculateRecency(timeDiff)
	return recencySimilarity
	
def compareNodeConceptTime(sentenceTreeNodeList, node1, node2, currentTime, nodeSentenceSubgraphsDynamic):
	#CHECKTHIS: requires calibration
	#CHECKTHIS: requires update - currently uses rudimentary combined minTimeDiff similarity comparison
	if(nodeSentenceSubgraphsDynamic):
		subgraphArtificalTime1 = calculateSubgraphArtificialTime(sentenceTreeNodeList, node1)
		subgraphArtificalTime2 = calculateSubgraphArtificialTime(sentenceTreeNodeList, node2)
	else:
		subgraphArtificalTime1 = getBranchConceptTime(node1)
		subgraphArtificalTime2 = getBranchConceptTime(node2)
	timeDiff = compareTime(subgraphArtificalTime1, subgraphArtificalTime2)
	return timeDiff
	
def calculateSubgraphArtificialTime(sentenceTreeNodeList, node):
	subgraphArtificalTime = 0
	subgraphArtificalTime, subgraphSize = calculateSubgraphArtificialTimeRecurse(sentenceTreeNodeList, node, subgraphArtificalTime, 0)
	subgraphArtificalTime = (subgraphArtificalTime / subgraphSize)
	return subgraphArtificalTime

def calculateSubgraphArtificialTimeRecurse(sentenceTreeNodeList, node, subgraphArtificalTime, subgraphSize):
	if(node.graphNodeType == graphNodeTypeLeaf):
		subgraphArtificalTime = subgraphArtificalTime + node.conceptTime
		subgraphSize = subgraphSize + 1
	for subgraphNode in node.graphNodeSourceList:	
		#if(subgraphNode in sentenceTreeNodeList):	#verify subgraph instance was referenced in current sentence
		subgraphArtificalTime, subgraphSize = calculateSubgraphArtificialTimeRecurse(sentenceTreeNodeList, subgraphNode, subgraphArtificalTime, subgraphSize)
	return subgraphArtificalTime, subgraphSize

def getBranchConceptTime(node1):
	if(calculateRecencyBasedOnNodeSentenceSubgraphsDynamicEmulate):
		conceptTime = node1.conceptTime/node1.subgraphSize
	else:
		conceptTime = node1.activationTime	#conceptTime
	return conceptTime

def compareTime(time1, time2):
	timeDiff = abs(time1 - time2)
	return timeDiff
	
#def calculateSubgraphMostRecentIdenticalConnection(sentenceTreeNodeList, node1, nodeToCompare, numberOfConnections1):
#	#TODO: verify calculate source to target connections only
#	numberOfConnections2 = calculateSubgraphNumberIdenticalConcepts2(sentenceTreeNodeList, node1, nodeToCompare, 0)
#	numberOfConnections1 += numberOfConnections2
#	for subgraphNode1 in node1.graphNodeSourceList:	
#		#if(subgraphNode1 in sentenceTreeNodeList):	#verify subgraph instance was referenced in current sentence
#		numberOfConnections1 = calculateSubgraphNumberIdenticalConcepts1(sentenceTreeNodeList, subgraphNode1, nodeToCompare, numberOfConnections1)
#	return numberOfConnections1	

def calculateConceptTimeLeafNode(sentenceTreeNodeList, lemma, currentTime):
	foundMostRecentInstanceNode, mostRecentInstanceNode, mostRecentInstanceTimeDiff = findMostRecentInstance(sentenceTreeNodeList, lemma, currentTime)
	if(not mostRecentInstanceNode):
		mostRecentInstanceTimeDiff = maxTimeDiff
	return mostRecentInstanceTimeDiff
	
def findMostRecentInstance(sentenceTreeNodeList, lemma, currentTime):	
	#print("findMostRecentInstance") 
	#calculates recency of most recent instance, and returns this instance
	foundMostRecentInstanceNode = False
	mostRecentInstanceNode = None
	mostRecentInstanceTimeDiff = None
	if(lemma in graphNodeDictionary):
		instanceDict2 = graphNodeDictionary[lemma]
		minTimeDiff = maxTimeDiff
		mostRecentInstanceNode = None
		for instanceID2, node2 in instanceDict2.items():
			if(node2.activationTime != currentTime):	#ignore instances that were added from same sentence	#OR: node2 is not in(sentenceTreeNodeList)
				timeDiff = calculateTimeDiffAbsolute(node2.activationTime, currentTime)
				#print("timeDiff = ", timeDiff)
				if(timeDiff < minTimeDiff):
					foundMostRecentInstanceNode = True
					minTimeDiff = timeDiff
					mostRecentInstanceNode = node2	#dict key

		mostRecentInstanceTimeDiff = minTimeDiff
	#print("mostRecentInstanceTimeDiff = ", mostRecentInstanceTimeDiff)
	return foundMostRecentInstanceNode, mostRecentInstanceNode, mostRecentInstanceTimeDiff

def calculateTimeDiffAbsolute(node2activationTime, currentTime):
	timeDiff = currentTime - node2activationTime
	return timeDiff
	
def calculateRecency(timeDiff):
	if(timeDiff == 0):
		recency = maxRecency	#1.0
	else:
		recency = 1.0/timeDiff
	return recency

def calculateTimeDiff(recency):
	timeDiff = 1.0/recency
	return timeDiff	

def calculateActivationTime(sentenceIndex):
	activationTime = sentenceIndex
	return activationTime
	
#not currently used;
def compareNodeLastActivationTime(node1, node2):
	timeDiffConnection = compareTime(node1.activationTime, node2.activationTime)
	return timeDiffConnection



#referencing:

def identifyBranchReferences(sentenceTreeNodeList, branchHeadNode, currentTime):
	for subgraphNode1 in branchHeadNode.graphNodeSourceList:	
		#if(subgraphNode1 in sentenceTreeNodeList):	#verify subgraph instance was referenced in current sentence (should always be true)
		branchReferenceFound, branchReference, _ = identifyBranchReference(sentenceTreeNodeList, subgraphNode1, currentTime)
		if(branchReferenceFound):
			replaceBranch(branchHeadNode, subgraphNode1, branchReference)
		else:
			identifyBranchReferences(sentenceTreeNodeList, subgraphNode1, currentTime)

def identifyBranchReference(sentenceTreeNodeList, subgraphNode1, currentTime):
	#CHECKTHIS: current optimisation/lookup limitations;
		#subgraphNode1.lemma must match referenceNode.lemma
		#subgraphNode1 branch structure must match referenceNode branch structure
	
	foundReference = False
	referenceNode = None
	maxReferenceMetric = 0

	if(subgraphNode1.lemma in graphNodeDictionary):
		#print("subgraphNode1.lemma = ", subgraphNode1.lemma)
		node1ConceptInstances = graphNodeDictionary[subgraphNode1.lemma]	#current limitation: only reference identical lemmas [future allow referencing based on word vector similarity]
		for instanceID1, instanceNode1 in node1ConceptInstances.items():
			#print("\tinstanceNode1.activationTime = ", instanceNode1.activationTime)
			if(instanceNode1.activationTime != currentTime):	#ignore instances that were added from same sentence	#OR: instanceNode1 is not in(sentenceTreeNodeList)
				frequency = calculateFrequencyReference(sentenceTreeNodeList, subgraphNode1, instanceNode1)
				recency = calculateRecencyReference(sentenceTreeNodeList, subgraphNode1, instanceNode1, currentTime)
				referenceMetric = calculateMetricReference(frequency, recency)
				#print("identifyBranchReference:")
				#print("\tfrequency = ", frequency)
				#print("\trecency = ", recency)
				#print("\treferenceMetric = ", referenceMetric)
				if(referenceMetric > metricThresholdToCreateReference):
					if(referenceMetric > maxReferenceMetric):
						print("identifyBranchReference: foundReference, referenceMetric = ", referenceMetric)
						print("\tfrequency = ", frequency)
						print("\trecency = ", recency)
						maxReferenceMetric = referenceMetric
						referenceNode = instanceNode1
						foundReference = True

	return foundReference, referenceNode, maxReferenceMetric
		
#replace local branch with referenced graph branch
def replaceBranch(branchHeadNode, subgraphNode1, branchReference):

	branchHeadNode.graphNodeSourceList.remove(subgraphNode1)
	branchHeadNode.graphNodeSourceList.append(branchReference)
	branchReference.graphNodeTargetList.append(branchHeadNode)
		
	#subgraphNode1.graphNodeTargetList.clear()	#not necessary	
	deleteBranch(subgraphNode1)

#delete local branch (without references)
def deleteBranch(branchHeadNode):
	for subgraphNode1 in branchHeadNode.graphNodeSourceList:	
		#if(subgraphNode1 in sentenceTreeNodeList):	#verify subgraph instance was referenced in current sentence (should always be true)
		removeNodeFromGraph(subgraphNode1)
		deleteBranch(subgraphNode1)
		del subgraphNode1
	
	
	
#tokenisation:

def tokeniseSentence(sentence):
	tokenList = spacyWordVectorGenerator(sentence)
	return tokenList

def getTokenWord(token):
	word = token.text
	return word
	
def getTokenLemma(token):
	lemma = token.lemma_
	if(token.lemma_ == '-PRON-'):
		lemma = token.text	#https://stackoverflow.com/questions/56966754/how-can-i-make-spacy-not-produce-the-pron-lemma
	return lemma
		
def getTokenWordVector(token):
	wordVector = token.vector	#cpu: type numpy
	return wordVector

def getTokenPOStag(token):
	#nlp in context prediction only (not certain)
	posTag = token.pos_
	return posTag



#python mean:

def mean(lst):
	return sum(lst) / len(lst)

def minMeanMaxList(lst):
	return (min(lst), mean(lst), max(lst))


